[2022-08-11 23:24:34,362] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2022-08-11 23:25:32,009] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:28:00,260] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:28:06,023] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/login [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 19, in login
    response = user_service.login(data)
TypeError: login() missing 1 required positional argument: 'login_req'
[2022-08-11 23:28:06,031] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:28:06] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 500 -
[2022-08-11 23:33:23,400] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:34:01,428] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:34:01] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-11 23:49:22,614] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:49:22] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 400 -
[2022-08-11 23:49:24,642] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:49:31,438] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/signup [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 51, in signup
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 99, in add_headers
    "userId": api_request.headers["x-user-id"],
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_X_USER_ID'
[2022-08-11 23:49:31,449] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:49:31] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 500 -
[2022-08-11 23:50:24,050] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:50:24] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:50:43,711] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:50:43] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:51:47,569] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:51:47] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:52:33,402] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:52:36,855] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:52:36] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:52:57,740] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:53:00,407] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:53:00] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:53:51,057] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:53:53,562] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:53:53] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:54:59,460] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:55:02,447] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:55:02] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:55:19,818] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:55:23,139] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:55:23] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:56:13,512] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:56:13] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:56:24,339] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:56:57,385] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:56:57] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 400 -
[2022-08-11 23:58:43,680] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:58:45,744] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:58:45] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:59:08,441] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:59:10,620] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/signup [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 51, in signup
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 106, in add_headers
    if api_headers["x-key"] == x_key:
KeyError: 'x-key'
[2022-08-11 23:59:10,626] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:59:10] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 500 -
[2022-08-12 00:00:33,730] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 11:47:54,093] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:15:43,774] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:16:29,096] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:16:29] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:18:09,820] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:18:17,749] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:18:17] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 12:19:06,787] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:19:12,012] {userservice.py:33} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:19:12,270] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:19:12] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:29:17,262] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:29:26,749] {userservice.py:22} Thread-1 INFO in userservice: Signing Up...
[2022-08-12 12:29:26,764] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:29:26] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 400 -
[2022-08-12 12:30:35,037] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:30:39,561] {userservice.py:22} Thread-1 INFO in userservice: Signing Up...
[2022-08-12 12:30:39,568] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:30:39] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 12:32:04,788] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:32:04] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 400 -
[2022-08-12 12:32:27,601] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:32:27] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 400 -
[2022-08-12 12:32:44,688] {userservice.py:75} Thread-4 INFO in userservice: Session Expired
[2022-08-12 12:32:44,688] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:32:44] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 403 -
[2022-08-12 12:33:02,675] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:33:06,741] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:33:06,750] {userservice.py:57} Thread-1 INFO in userservice: {'email': 'vishal.mahuli@tarento.com', 'password': b'$2b$12$8SlPGiE0PsL9XHgMme2oqOgczi/CxO.EOTw0uViZDfoaonbCra/ki', 'username': 'vishal.mahuli@tarento.com', 'userId': '98746fd1-e9e0-4050-9f44-effc1cd3a25a'}
[2022-08-12 12:33:07,066] {userservice.py:59} Thread-1 INFO in userservice: b'$2b$12$i9yLSw0MYRIc2.9AIufC5.eCyFTJ3u6efaDJXnyi7FgBIsFrfx83C'
[2022-08-12 12:33:07,067] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:33:07] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:33:55,225] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:34:01,365] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:34:01,370] {userservice.py:57} Thread-1 INFO in userservice: {'email': 'vishal.mahuli@tarento.com', 'password': b'$2b$12$8SlPGiE0PsL9XHgMme2oqOgczi/CxO.EOTw0uViZDfoaonbCra/ki', 'username': 'vishal.mahuli@tarento.com', 'userId': '98746fd1-e9e0-4050-9f44-effc1cd3a25a'}
[2022-08-12 12:34:01,624] {userservice.py:59} Thread-1 INFO in userservice: b'$2b$12$yYri9u5wh7iBQrw5XvdOwebLSPc3SzyJ1t1l/hkzm/BUkWx6bhXVG'
[2022-08-12 12:34:01,625] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:34:01] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:41:49,374] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:41:57,689] {userservice.py:52} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:41:57,712] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:41:57] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:42:32,551] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:42:37,964] {userservice.py:52} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:42:37,991] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:42:37] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:51:14,873] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:51:23,147] {userservice.py:52} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:51:23,651] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:51:23] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:51:39,493] {app.py:1891} Thread-2 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/signup [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 51, in signup
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 122, in add_headers
    "userId": api_request.headers["x-user-id"],
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_X_USER_ID'
[2022-08-12 12:51:39,504] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:51:39] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 500 -
[2022-08-12 12:54:09,831] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:54:17,505] {userservice.py:41} Thread-1 INFO in userservice: Deleting User...
[2022-08-12 12:54:17,512] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:54:17] "[37mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 200 -
[2022-08-12 12:54:34,654] {userservice.py:24} Thread-2 INFO in userservice: Signing Up...
[2022-08-12 12:54:34,910] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:54:34] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 12:54:43,417] {userservice.py:52} Thread-3 INFO in userservice: Logging in...
[2022-08-12 12:54:43,887] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:54:43] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:55:55,399] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:56:02,353] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:56:02,357] {ddsutils.py:27} Thread-1 INFO in ddsutils: pwd: b'$2b$12$E1bvtT7C2cJZvl6rSxlwseM4iGE/hON2fCSQAO9wVP7NUZbGsne6e' | ip_pwd: 123456
[2022-08-12 12:56:02,861] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:56:02] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:57:32,077] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:57:35,981] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:57:36,241] {ddsutils.py:24} Thread-1 INFO in ddsutils: pwd: b'$2b$12$E1bvtT7C2cJZvl6rSxlwseM4iGE/hON2fCSQAO9wVP7NUZbGsne6e' | ip_pwd: b'$2b$12$DDT4ajThARjVh1JUtqZNoeoZAotc3iti2tdiH4zC6GrA3eF360Wxe'
[2022-08-12 12:57:36,492] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:57:36] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 13:01:58,445] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 13:02:05,379] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 13:02:05,402] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:02:05] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 13:04:47,818] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 13:04:54,682] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 13:04:54,743] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:04:54] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 13:13:32,061] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 13:13:40,823] {userservice.py:39} Thread-1 INFO in userservice: Deleting User...
[2022-08-12 13:13:40,831] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:13:40] "[37mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 200 -
[2022-08-12 13:13:43,730] {userservice.py:22} Thread-2 INFO in userservice: Signing Up...
[2022-08-12 13:13:43,975] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:13:43] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 13:13:50,813] {userservice.py:50} Thread-3 INFO in userservice: Logging in...
[2022-08-12 13:13:51,068] {ddsutils.py:25} Thread-3 INFO in ddsutils: b'$2b$12$KMBd.ohO3GL7UTu92UejJeStJGkz0rqSrYvpk0hTlvM193xZQ7UWe'
[2022-08-12 13:13:51,068] {ddsutils.py:26} Thread-3 INFO in ddsutils: b'$2b$12$KMBd.ohO3GL7UTu92UejJeStJGkz0rqSrYvpk0hTlvM193xZQ7UWe'
[2022-08-12 13:13:51,162] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:13:51] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 14:10:01,076] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:10:07,131] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/document/upload [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 82, in doc_upload
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 131, in add_headers
    data["metadata"] = headers
TypeError: 'NoneType' object does not support item assignment
[2022-08-12 14:10:07,138] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:10:07] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 500 -
[2022-08-12 14:10:45,118] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:11:34,636] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:11:38,853] {userservice.py:78} Thread-1 INFO in userservice: Session Expired
[2022-08-12 14:11:38,853] {userservice.py:84} Thread-1 INFO in userservice: Logging out...
[2022-08-12 14:11:38,863] {userservice.py:93} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 14:11:38,863] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:11:38] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 403 -
[2022-08-12 14:11:51,228] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 14:11:51,492] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:11:51] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 14:12:12,999] {ddsservice.py:27} Thread-3 INFO in ddsservice: 6581403a-ed15-4269-8a9c-18f099011b60 | Uploading file...
[2022-08-12 14:12:12,999] {ddsservice.py:46} Thread-3 INFO in ddsservice: 6581403a-ed15-4269-8a9c-18f099011b60 | Parsing metadata file...
[2022-08-12 14:12:13,457] {ddsservice.py:50} Thread-3 INFO in ddsservice: Metadata Filename: test-metadata.csv, MIME Type: text/csv
[2022-08-12 14:12:13,491] {ddsservice.py:30} Thread-3 INFO in ddsservice: 6581403a-ed15-4269-8a9c-18f099011b60 | Metadata file couldn't be parsed!
[2022-08-12 14:12:13,493] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:12:13] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 400 -
[2022-08-12 14:14:18,575] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:14:25,185] {ddsservice.py:27} Thread-1 INFO in ddsservice: 1600b421-8f26-46d1-a762-1d1db70e7db4 | Uploading file...
[2022-08-12 14:14:25,185] {ddsservice.py:46} Thread-1 INFO in ddsservice: 1600b421-8f26-46d1-a762-1d1db70e7db4 | Parsing metadata file...
[2022-08-12 14:14:25,701] {ddsservice.py:50} Thread-1 INFO in ddsservice: Metadata Filename: test-metadata.csv, MIME Type: text/csv
[2022-08-12 14:14:25,738] {ddsservice.py:30} Thread-1 INFO in ddsservice: 1600b421-8f26-46d1-a762-1d1db70e7db4 | Metadata file couldn't be parsed!
[2022-08-12 14:14:25,743] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:14:25] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 400 -
[2022-08-12 14:19:02,836] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:09:55,463] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:10:28,703] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:10:34,703] {userservice.py:78} Thread-1 INFO in userservice: Session Expired
[2022-08-12 15:10:34,703] {userservice.py:84} Thread-1 INFO in userservice: Logging out...
[2022-08-12 15:10:34,709] {userservice.py:93} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 15:10:34,710] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:10:34] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 403 -
[2022-08-12 15:10:42,191] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 15:10:42,466] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:10:42] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 15:11:01,694] {ddsservice.py:27} Thread-3 INFO in ddsservice: 9e2776ac-0e20-436a-b386-0c502934ea7d | Uploading file...
[2022-08-12 15:11:01,695] {ddsservice.py:46} Thread-3 INFO in ddsservice: 9e2776ac-0e20-436a-b386-0c502934ea7d | Parsing metadata file...
[2022-08-12 15:11:02,171] {ddsservice.py:50} Thread-3 INFO in ddsservice: Metadata Filename: test-metadata - Sheet1.csv, MIME Type: text/csv
[2022-08-12 15:11:02,172] {ddsservice.py:84} Thread-3 INFO in ddsservice: 9e2776ac-0e20-436a-b386-0c502934ea7d | Filename: UEMSMacAgent.zip, MIME Type: application/zip
[2022-08-12 15:11:02,172] {ddsservice.py:95} Thread-3 INFO in ddsservice: 9e2776ac-0e20-436a-b386-0c502934ea7d | Saving to local store...
[2022-08-12 15:11:02,208] {ddsservice.py:97} Thread-3 INFO in ddsservice: 9e2776ac-0e20-436a-b386-0c502934ea7d | Pushing to object store...
[2022-08-12 15:11:02,247] {ddsservice.py:42} Thread-3 INFO in ddsservice: 9e2776ac-0e20-436a-b386-0c502934ea7d | File upload failed.
[2022-08-12 15:11:02,250] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:11:02] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 400 -
[2022-08-12 15:21:11,591] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:21:19,004] {userservice.py:73} Thread-1 INFO in userservice: Session Expired
[2022-08-12 15:21:19,005] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:21:19] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 403 -
[2022-08-12 15:21:25,541] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 15:21:25,543] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:21:25] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 15:21:33,114] {userservice.py:22} Thread-3 INFO in userservice: Signing Up...
[2022-08-12 15:21:33,499] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:21:33] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 15:21:36,431] {userservice.py:50} Thread-4 INFO in userservice: Logging in...
[2022-08-12 15:21:36,797] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:21:36] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 15:22:09,769] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:22:15,157] {ddsservice.py:27} Thread-1 INFO in ddsservice: 0472f338-ed45-4119-8738-cc7611e2e538 | Uploading file...
[2022-08-12 15:22:15,157] {ddsservice.py:46} Thread-1 INFO in ddsservice: 0472f338-ed45-4119-8738-cc7611e2e538 | Parsing metadata file...
[2022-08-12 15:22:15,662] {ddsservice.py:50} Thread-1 INFO in ddsservice: Metadata Filename: test-metadata - Sheet1.csv, MIME Type: text/csv
[2022-08-12 15:22:15,664] {ddsservice.py:84} Thread-1 INFO in ddsservice: 0472f338-ed45-4119-8738-cc7611e2e538 | Filename: UEMSMacAgent.zip, MIME Type: application/zip
[2022-08-12 15:22:15,664] {ddsservice.py:95} Thread-1 INFO in ddsservice: 0472f338-ed45-4119-8738-cc7611e2e538 | Saving to local store...
[2022-08-12 15:22:15,690] {ddsservice.py:97} Thread-1 INFO in ddsservice: 0472f338-ed45-4119-8738-cc7611e2e538 | Pushing to object store...
[2022-08-12 15:22:15,691] {ddsutils.py:34} Thread-1 INFO in ddsutils: Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/0472f338-ed45-4119-8738-cc7611e2e538___UEMSMacAgent.zip to azure at 0472f338-ed45-4119-8738-cc7611e2e538/UEMSMacAgent.zip on a new fork......
[2022-08-12 15:22:15,692] {ddsutils.py:34} Thread-1 INFO in ddsutils: Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/0472f338-ed45-4119-8738-cc7611e2e538___metadata___test-metadata - Sheet1.csv to azure at 0472f338-ed45-4119-8738-cc7611e2e538/metadata.csv on a new fork......
[2022-08-12 15:22:15,692] {ddsservice.py:38} Thread-1 INFO in ddsservice: 0472f338-ed45-4119-8738-cc7611e2e538 | Saving metadata....
[2022-08-12 15:22:15,808] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:22:15] "[37mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 200 -
[2022-08-12 15:25:36,178] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:25:42,135] {ddsservice.py:27} Thread-1 INFO in ddsservice: 1440384b-a101-4855-84bf-1f1e0fd77899 | Uploading file...
[2022-08-12 15:25:42,135] {ddsservice.py:46} Thread-1 INFO in ddsservice: 1440384b-a101-4855-84bf-1f1e0fd77899 | Parsing metadata file...
[2022-08-12 15:25:42,594] {ddsservice.py:50} Thread-1 INFO in ddsservice: Metadata Filename: test-metadata - Sheet1.csv, MIME Type: text/csv
[2022-08-12 15:25:42,595] {ddsservice.py:84} Thread-1 INFO in ddsservice: 1440384b-a101-4855-84bf-1f1e0fd77899 | Filename: UEMSMacAgent.zip, MIME Type: application/zip
[2022-08-12 15:25:42,595] {ddsservice.py:95} Thread-1 INFO in ddsservice: 1440384b-a101-4855-84bf-1f1e0fd77899 | Saving to local store...
[2022-08-12 15:25:42,623] {ddsservice.py:97} Thread-1 INFO in ddsservice: 1440384b-a101-4855-84bf-1f1e0fd77899 | Pushing to object store...
[2022-08-12 15:25:42,624] {ddsutils.py:39} Thread-1 INFO in ddsutils: Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/1440384b-a101-4855-84bf-1f1e0fd77899___UEMSMacAgent.zip to azure at 1440384b-a101-4855-84bf-1f1e0fd77899/UEMSMacAgent.zip synchronously....
[2022-08-12 15:25:51,175] {ddsutils.py:39} Thread-1 INFO in ddsutils: Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/1440384b-a101-4855-84bf-1f1e0fd77899___metadata___test-metadata - Sheet1.csv to azure at 1440384b-a101-4855-84bf-1f1e0fd77899/metadata.csv synchronously....
[2022-08-12 15:25:51,419] {ddsservice.py:38} Thread-1 INFO in ddsservice: 1440384b-a101-4855-84bf-1f1e0fd77899 | Saving metadata....
[2022-08-12 15:25:51,427] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:25:51] "[37mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 200 -
[2022-08-12 15:31:44,285] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:31:44] "[31m[1mGET /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 405 -
[2022-08-12 15:31:50,733] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:31:56,036] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:31:56] "[37mGET /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:33:24,774] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:33:41,915] {ddsservice.py:107} Thread-1 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:33:41,920] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:33:41] "[37mGET /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:35:04,529] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:35:10,673] {ddsservice.py:107} Thread-1 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:35:10,676] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:35:10] "[37mGET /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:45:44,635] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:45:50,912] {userservice.py:78} Thread-1 INFO in userservice: Session Expired
[2022-08-12 15:45:50,912] {userservice.py:84} Thread-1 INFO in userservice: Logging out...
[2022-08-12 15:45:50,917] {userservice.py:93} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 15:45:50,918] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:45:50] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 403 -
[2022-08-12 15:45:57,802] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 15:45:58,068] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:45:58] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 15:46:15,949] {ddsservice.py:99} Thread-3 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:46:15,953] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:46:15] "[37mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:46:16,326] {ddsservice.py:99} Thread-4 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:46:16,327] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:46:16] "[37mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:49:04,721] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:49:48,070] {ddsservice.py:99} Thread-1 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:49:48,074] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:49:48] "[37mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:51:48,611] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:51:54,893] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/logout [POST]
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-dus/DMU-DataDaan/backend/dmu-datastore/controller/ddscontroller.py", line 36, in logout
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-dus/DMU-DataDaan/backend/dmu-datastore/controller/ddscontroller.py", line 128, in add_headers
    "userId": api_request.headers["x-user-id"],
  File "/Library/Python/3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_X_USER_ID'
[2022-08-12 15:51:54,902] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:51:54] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/logout HTTP/1.1[0m" 500 -
[2022-08-12 15:52:42,636] {userservice.py:84} Thread-2 INFO in userservice: Logging out...
[2022-08-12 15:52:42,641] {userservice.py:88} Thread-2 INFO in userservice: Logged out already!
[2022-08-12 15:52:42,642] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:52:42] "[37mPOST /dmu-datastore/data-upload-service/v1/logout HTTP/1.1[0m" 200 -
[2022-08-12 15:52:46,814] {ddsservice.py:99} Thread-3 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:52:46,817] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:52:46] "[37mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 15:55:01,970] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 15:55:07,082] {userservice.py:84} Thread-1 INFO in userservice: Logging out...
[2022-08-12 15:55:07,086] {userservice.py:88} Thread-1 INFO in userservice: Logged out already!
[2022-08-12 15:55:07,087] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:55:07] "[37mPOST /dmu-datastore/data-upload-service/v1/logout HTTP/1.1[0m" 200 -
[2022-08-12 15:56:01,622] {ddsservice.py:99} Thread-2 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 15:56:01,625] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 15:56:01] "[37mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 16:01:39,416] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 16:01:43,989] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:01:43,993] {userservice.py:85} Thread-1 INFO in userservice: Logging out...
[2022-08-12 16:01:44,003] {userservice.py:94} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 16:01:44,003] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:01:44] "[37mGET /dmu-datastore/data-upload-service/v1/logout HTTP/1.1[0m" 200 -
[2022-08-12 16:01:46,999] {userservice.py:71} Thread-2 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:01:47,002] {userservice.py:74} Thread-2 INFO in userservice: Invalid Token!
[2022-08-12 16:01:47,003] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:01:47] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 403 -
[2022-08-12 16:02:25,469] {userservice.py:50} Thread-3 INFO in userservice: Logging in...
[2022-08-12 16:02:25,734] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:02:25] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 16:02:42,202] {userservice.py:71} Thread-4 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:02:42,209] {ddsservice.py:99} Thread-4 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 16:02:42,212] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:02:42] "[37mPOST /dmu-datastore/data-upload-service/v1/document/search HTTP/1.1[0m" 200 -
[2022-08-12 16:44:42,903] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 16:45:15,979] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 16:45:16,290] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:45:16] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 16:45:59,803] {userservice.py:71} Thread-2 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:45:59,815] {ddsservice.py:27} Thread-2 INFO in ddsservice: 4e2a993f-7f8d-432d-bfac-af7f059381e1 | Uploading file...
[2022-08-12 16:45:59,815] {ddsservice.py:46} Thread-2 INFO in ddsservice: 4e2a993f-7f8d-432d-bfac-af7f059381e1 | Parsing metadata file...
[2022-08-12 16:46:48,852] {ddsservice.py:50} Thread-2 INFO in ddsservice: Metadata Filename: asr_iiit_cstd_ulca_te_j.tsv, MIME Type: text/tab-separated-values
[2022-08-12 16:46:48,886] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:46:48] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 400 -
[2022-08-12 16:48:52,064] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 16:48:56,510] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:48:56,515] {ddsservice.py:27} Thread-1 INFO in ddsservice: 38ea5610-223f-49ad-83b3-84e72313a843 | Uploading file...
[2022-08-12 16:48:56,515] {ddsservice.py:47} Thread-1 INFO in ddsservice: 38ea5610-223f-49ad-83b3-84e72313a843 | Parsing metadata file...
[2022-08-12 16:49:43,130] {ddsservice.py:51} Thread-1 INFO in ddsservice: Metadata Filename: asr_iiit_cstd_ulca_te_j.tsv, MIME Type: text/tab-separated-values
[2022-08-12 16:49:43,132] {ddsservice.py:32} Thread-1 INFO in ddsservice: {'status': 'FAILED', 'message': 'Unsupported Metadata File Type!'}
[2022-08-12 16:49:43,195] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:49:43] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 400 -
[2022-08-12 16:51:26,809] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 16:51:31,195] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:51:31,199] {ddsservice.py:27} Thread-1 INFO in ddsservice: bee9d6c6-4b88-4a9d-a970-1ccd01038b61 | Uploading file...
[2022-08-12 16:51:31,199] {ddsservice.py:49} Thread-1 INFO in ddsservice: bee9d6c6-4b88-4a9d-a970-1ccd01038b61 | Parsing metadata file...
[2022-08-12 16:52:13,978] {ddsservice.py:53} Thread-1 INFO in ddsservice: Metadata Filename: asr_iiit_cstd_ulca_te_j.tsv, MIME Type: text/tab-separated-values
[2022-08-12 16:52:13,981] {ddsservice.py:33} Thread-1 INFO in ddsservice: bee9d6c6-4b88-4a9d-a970-1ccd01038b61 | Metadata file couldn't be parsed!
[2022-08-12 16:52:13,994] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:52:13] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 400 -
[2022-08-12 16:57:40,257] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 16:57:55,252] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 16:57:55,260] {ddsservice.py:27} Thread-1 INFO in ddsservice: ce04d2e7-2ed1-4e20-86f9-4668eb035ea1 | Uploading file...
[2022-08-12 16:57:55,261] {ddsservice.py:49} Thread-1 INFO in ddsservice: ce04d2e7-2ed1-4e20-86f9-4668eb035ea1 | Parsing metadata file...
[2022-08-12 16:58:53,572] {ddsservice.py:53} Thread-1 INFO in ddsservice: Metadata Filename: test-metadata - Sheet1.csv, MIME Type: text/csv
[2022-08-12 16:58:53,576] {ddsservice.py:80} Thread-1 INFO in ddsservice: ce04d2e7-2ed1-4e20-86f9-4668eb035ea1 | Filename: asr_iiit_cstd_ulca_te_j.zip, MIME Type: application/zip
[2022-08-12 16:58:53,577] {ddsservice.py:91} Thread-1 INFO in ddsservice: ce04d2e7-2ed1-4e20-86f9-4668eb035ea1 | Saving to local store...
[2022-08-12 16:59:00,155] {ddsservice.py:93} Thread-1 INFO in ddsservice: ce04d2e7-2ed1-4e20-86f9-4668eb035ea1 | Pushing to object store...
[2022-08-12 16:59:00,264] {ddsservice.py:45} Thread-1 INFO in ddsservice: ce04d2e7-2ed1-4e20-86f9-4668eb035ea1 | File upload failed.
[2022-08-12 16:59:00,632] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 16:59:00] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 400 -
[2022-08-12 17:04:49,663] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 17:04:56,858] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 17:04:56,862] {userservice.py:79} Thread-1 INFO in userservice: Session Expired
[2022-08-12 17:04:56,862] {userservice.py:85} Thread-1 INFO in userservice: Logging out...
[2022-08-12 17:04:56,867] {userservice.py:94} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 17:04:56,867] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:04:56] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 403 -
[2022-08-12 17:05:00,836] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 17:05:01,102] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:05:01] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 17:05:19,086] {userservice.py:71} Thread-3 INFO in userservice: Checking if the user session is active.....
[2022-08-12 17:05:19,089] {ddsservice.py:27} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Initiating...
[2022-08-12 17:05:19,089] {ddsservice.py:49} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Parsing metadata file...
[2022-08-12 17:06:10,358] {ddsservice.py:53} Thread-3 INFO in ddsservice: Metadata Filename: test-metadata - Sheet1.csv, MIME Type: text/csv
[2022-08-12 17:06:10,362] {ddsservice.py:78} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Processing Zip File......
[2022-08-12 17:06:10,362] {ddsservice.py:81} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Filename: asr_iiit_cstd_ulca_te_j.zip, MIME Type: application/zip
[2022-08-12 17:06:10,362] {ddsservice.py:92} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Saving to local store...
[2022-08-12 17:06:15,062] {ddsservice.py:94} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Pushing to object store...
[2022-08-12 17:06:15,067] {ddsutils.py:39} Thread-3 INFO in ddsutils: Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/696d183d-6347-49ab-aa1a-36f8a854bc79___asr_iiit_cstd_ulca_te_j.zip to azure at 696d183d-6347-49ab-aa1a-36f8a854bc79/asr_iiit_cstd_ulca_te_j.zip synchronously....
[2022-08-12 17:23:14,919] {ddsutils.py:39} Thread-3 INFO in ddsutils: Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/696d183d-6347-49ab-aa1a-36f8a854bc79___metadata___test-metadata - Sheet1.csv to azure at 696d183d-6347-49ab-aa1a-36f8a854bc79/metadata.csv synchronously....
[2022-08-12 17:23:15,160] {ddsservice.py:41} Thread-3 INFO in ddsservice: 696d183d-6347-49ab-aa1a-36f8a854bc79 | Saving metadata....
[2022-08-12 17:23:15,287] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:23:15] "[37mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 200 -
[2022-08-12 17:30:09,826] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 17:30:29,080] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 17:30:29,084] {userservice.py:79} Thread-1 INFO in userservice: Session Expired
[2022-08-12 17:30:29,084] {userservice.py:85} Thread-1 INFO in userservice: Logging out...
[2022-08-12 17:30:29,088] {userservice.py:94} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 17:30:29,089] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:30:29] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 403 -
[2022-08-12 17:30:34,380] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 17:30:34,643] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:30:34] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 17:30:57,104] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 17:31:01,972] {userservice.py:71} Thread-1 INFO in userservice: Checking if the user session is active.....
[2022-08-12 17:31:01,976] {ddsservice.py:27} Thread-1 INFO in ddsservice: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Initiating...
[2022-08-12 17:31:01,976] {ddsservice.py:50} Thread-1 INFO in ddsservice: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Parsing metadata file...
[2022-08-12 17:31:56,936] {ddsservice.py:78} Thread-1 INFO in ddsservice: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Processing Zip File......
[2022-08-12 17:31:56,937] {ddsservice.py:91} Thread-1 INFO in ddsservice: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Saving to local store...
[2022-08-12 17:32:03,472] {ddsservice.py:93} Thread-1 INFO in ddsservice: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Pushing to object store...
[2022-08-12 17:32:03,478] {ddsutils.py:37} Thread-1 INFO in ddsutils: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/7fbb7796-303c-4595-a1a3-78c7b561ebde___metadata___asr_iiit_cstd_ulca_te_j.tsv to azure at 7fbb7796-303c-4595-a1a3-78c7b561ebde/metadata.csv on a new fork......
[2022-08-12 17:32:03,480] {ddsutils.py:37} Thread-1 INFO in ddsutils: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Pushing /Users/vishalmahuli/Desktop/dmu-dus/docs/7fbb7796-303c-4595-a1a3-78c7b561ebde___asr_iiit_cstd_ulca_te_j.zip to azure at 7fbb7796-303c-4595-a1a3-78c7b561ebde/asr_iiit_cstd_ulca_te_j.zip on a new fork......
[2022-08-12 17:32:03,480] {ddsservice.py:42} Thread-1 INFO in ddsservice: 7fbb7796-303c-4595-a1a3-78c7b561ebde | Saving metadata to mongo store....
[2022-08-12 17:32:03,839] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:32:03] "[37mPOST /dmu-datastore/data-upload-service/v1/file/upload HTTP/1.1[0m" 200 -
[2022-08-12 17:34:13,366] {userservice.py:71} Thread-4 INFO in userservice: Checking if the user session is active.....
[2022-08-12 17:34:13,375] {ddsservice.py:102} Thread-4 INFO in ddsservice: Searching for User Uploads......
[2022-08-12 17:34:13,376] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:34:13] "[37mPOST /dmu-datastore/data-upload-service/v1/upload/search HTTP/1.1[0m" 200 -
[2022-08-12 17:50:31,344] {userservice.py:71} Thread-5 INFO in userservice: Checking if the user session is active.....
[2022-08-12 17:50:31,353] {userservice.py:79} Thread-5 INFO in userservice: Session Expired
[2022-08-12 17:50:31,353] {userservice.py:85} Thread-5 INFO in userservice: Logging out...
[2022-08-12 17:50:31,360] {userservice.py:94} Thread-5 INFO in userservice: Logged out successfully!
[2022-08-12 17:50:31,362] {_internal.py:113} Thread-5 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 17:50:31] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/upload/search HTTP/1.1[0m" 403 -
